language: cpp
sudo: required
<<<<<<< HEAD
compiler: gcc
env: QT_BASE="56"

=======
matrix:
    include:
    - os: linux
        dist: trusty
        compiler: gcc
        env:
            - QT_BASE=56
    - os: linux
        dist: trusty    
        compiler: gcc
        env:
            - QT_BASE=57
>>>>>>> f23595ca6f032e181360b066426343ac866406fa
before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y;
    - sudo apt-get update -qq;
install:
    - sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh;

script:
    - qmake -v
    - qmake -r
    - make
notifications:
    email: false
